export default {
  overview: 'Overview',
  _: {
    type: 'separator',
    title: 'Essential',
  },
  metadata: 'Metadata',
  hero: 'Hero Section',
  nav: 'Navigation',
  footer: 'Footer',
  license: 'License',
  _2: {
    type: 'separator',
    title: 'Optional',
  },
  posts: 'Posts',
  toc: 'Table of Contents',
  'color-scheme': 'Color Scheme',
  'builtin-components': 'Built-in Components',
  'smooth-scroll': 'Smooth Scroll',
  _3: {
    type: 'separator',
    title: 'Advanced',
  },
  insertions: 'Insertions',
  icons: 'Icons',
  'date-display-format': 'Date Display Format',
  cdn: 'CDN',
  'scroll-reveal': 'Scroll Reveal',
  'view-transition': 'View Transition',
  'hero-exit-while-scrolling': 'Hero Exit While Scrolling',
  'nav-blur-gradient': 'Nav Blur Gradient',
  'rainbow-banner': 'Rainbow Banner',
  squircle: 'Squircle Corners',
}
