export default {
  overview: '总览',
  _: {
    type: 'separator',
    title: '基础',
  },
  metadata: '元数据',
  hero: '首屏区域',
  nav: '导航栏',
  footer: '页脚',
  license: '许可证',
  _2: {
    type: 'separator',
    title: '可选',
  },
  posts: '文章',
  toc: '目录',
  'color-scheme': '配色方案',
  'builtin-components': '内置组件',
  'smooth-scroll': '平滑滚动',
  _3: {
    type: 'separator',
    title: '高级',
  },
  insertions: '注入',
  icons: '图标',
  'date-display-format': '日期显示格式',
  cdn: 'CDN',
  'scroll-reveal': '滚动显现',
  'view-transition': '视图过渡',
  'hero-exit-while-scrolling': '滚动时首屏退出',
  'nav-blur-gradient': '导航模糊渐变',
  'rainbow-banner': '彩虹横幅',
  squircle: 'Squircle 圆角',
}
